name: Static Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  static_code_analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn clean compile

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          token: ${{ secrets.SONAR_TOKEN }}
          extraProperties: |
            sonar.projectKey=your_project_key
            sonar.sources=src
            sonar.java.binaries=target/classes
            sonar.java.libraries=target/lib/**/*.jar
            sonar.coverage.exclusions=**/generated/**/*, **/test/**/*
            sonar.exclusions=**/generated/**/*, **/test/**/*
            sonar.language=java
            sonar.java.source=17
            sonar.java.target=17
            sonar.jacoco.reportPaths=target/jacoco.exec
            sonar.junit.reportPaths=target/surefire-reports
            sonar.scm.disabled=true
            sonar.report.export.path=sonar-report.json
